Repository volks73/cargo-wix, pull requests merged in 2023-09, with the labels that each got.

#209 add --target-bin-dir to execute
  src/create.rs
  src/main.rs
  src/templates/main.wxs.mustache
Labels: enhancement

#211 fix: fix broken parsing in 'print' command
  src/main.rs
Labels: bug

#216 Changed rust version to v1.70.0 and dependencies
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
Labels: enhancement

#224 Release 0.3.6
  Cargo.lock
  Cargo.toml
Labels: enhancement

#239 fix: ultra-stabilize binary ordering
  src/print/wxs.rs
Labels: bug

#244 Fix typos
  src/initialize.rs
  src/lib.rs
  src/main.rs
  src/print/mod.rs
  src/print/wxs.rs
  src/purge.rs
  src/templates/main.wxs.mustache
  tests/common/mod.rs
Labels: bug, documentation
